-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Mutation exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


type alias CompleteOrderRequiredArguments =
    { id : Api.ScalarCodecs.Id }


completeOrder :
    CompleteOrderRequiredArguments
    -> SelectionSet decodesTo Api.Object.OrderResult
    -> SelectionSet (Maybe decodesTo) RootMutation
completeOrder requiredArgs object_ =
    Object.selectionForCompositeField "completeOrder" [ Argument.required "id" requiredArgs.id (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId) ] object_ (identity >> Decode.nullable)


type alias CreateMenuItemRequiredArguments =
    { input : Api.InputObject.MenuItemInput }


createMenuItem :
    CreateMenuItemRequiredArguments
    -> SelectionSet decodesTo Api.Object.MenuItemResult
    -> SelectionSet (Maybe decodesTo) RootMutation
createMenuItem requiredArgs object_ =
    Object.selectionForCompositeField "createMenuItem" [ Argument.required "input" requiredArgs.input Api.InputObject.encodeMenuItemInput ] object_ (identity >> Decode.nullable)


type alias PlaceOrderRequiredArguments =
    { input : Api.InputObject.PlaceOrderInput }


placeOrder :
    PlaceOrderRequiredArguments
    -> SelectionSet decodesTo Api.Object.OrderResult
    -> SelectionSet (Maybe decodesTo) RootMutation
placeOrder requiredArgs object_ =
    Object.selectionForCompositeField "placeOrder" [ Argument.required "input" requiredArgs.input Api.InputObject.encodePlaceOrderInput ] object_ (identity >> Decode.nullable)


type alias ReadyOrderRequiredArguments =
    { id : Api.ScalarCodecs.Id }


readyOrder :
    ReadyOrderRequiredArguments
    -> SelectionSet decodesTo Api.Object.OrderResult
    -> SelectionSet (Maybe decodesTo) RootMutation
readyOrder requiredArgs object_ =
    Object.selectionForCompositeField "readyOrder" [ Argument.required "id" requiredArgs.id (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId) ] object_ (identity >> Decode.nullable)
