-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (..)


type Category
    = Category


type InputError
    = InputError


type MenuItem
    = MenuItem


type MenuItemResult
    = MenuItemResult


type Order
    = Order


type OrderItem
    = OrderItem


type OrderResult
    = OrderResult
