-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.ScalarCodecs exposing (..)

import Api.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Date =
    Api.Scalar.Date


type alias Decimal =
    Api.Scalar.Decimal


type alias Id =
    Api.Scalar.Id


codecs : Api.Scalar.Codecs Date Decimal Id
codecs =
    Api.Scalar.defineCodecs
        { codecDate = defaultCodecs.codecDate
        , codecDecimal = defaultCodecs.codecDecimal
        , codecId = defaultCodecs.codecId
        }
