-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Subscription exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


newOrder :
    SelectionSet decodesTo Api.Object.Order
    -> SelectionSet (Maybe decodesTo) RootSubscription
newOrder object_ =
    Object.selectionForCompositeField "newOrder" [] object_ (identity >> Decode.nullable)


type alias UpdateOrderRequiredArguments =
    { id : Api.ScalarCodecs.Id }


updateOrder :
    UpdateOrderRequiredArguments
    -> SelectionSet decodesTo Api.Object.Order
    -> SelectionSet (Maybe decodesTo) RootSubscription
updateOrder requiredArgs object_ =
    Object.selectionForCompositeField "updateOrder" [ Argument.required "id" requiredArgs.id (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId) ] object_ (identity >> Decode.nullable)
