-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Category exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


description : SelectionSet (Maybe String) Api.Object.Category
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


items :
    SelectionSet decodesTo Api.Object.MenuItem
    -> SelectionSet (Maybe (List decodesTo)) Api.Object.Category
items object_ =
    Object.selectionForCompositeField "items" [] object_ (identity >> Decode.list >> Decode.nullable)


itemz :
    SelectionSet decodesTo Api.Object.MenuItem
    -> SelectionSet (Maybe (List decodesTo)) Api.Object.Category
itemz object_ =
    Object.selectionForCompositeField "itemz" [] object_ (identity >> Decode.list >> Decode.nullable)


name : SelectionSet String Api.Object.Category
name =
    Object.selectionForField "String" "name" [] Decode.string
