-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.MenuItem exposing (..)

import Api.Enum.DateFormat
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


type alias AddedOnOptionalArguments =
    { format : OptionalArgument Api.Enum.DateFormat.DateFormat }


{-| When the menu item was added
-}
addedOn :
    (AddedOnOptionalArguments -> AddedOnOptionalArguments)
    -> SelectionSet (Maybe String) Api.Object.MenuItem
addedOn fillInOptionals =
    let
        filledInOptionals =
            fillInOptionals { format = Absent }

        optionalArgs =
            [ Argument.optional "format" filledInOptionals.format (Encode.enum Api.Enum.DateFormat.toString) ]
                |> List.filterMap identity
    in
    Object.selectionForField "(Maybe String)" "addedOn" optionalArgs (Decode.string |> Decode.nullable)


{-| The description of the menu item
-}
description : SelectionSet (Maybe String) Api.Object.MenuItem
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


{-| The id of the menu item
-}
id : SelectionSet Api.ScalarCodecs.Id Api.Object.MenuItem
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| The name of the menu item
-}
name : SelectionSet String Api.Object.MenuItem
name =
    Object.selectionForField "String" "name" [] Decode.string


{-| The price of the menu item
-}
price : SelectionSet Api.ScalarCodecs.Decimal Api.Object.MenuItem
price =
    Object.selectionForField "ScalarCodecs.Decimal" "price" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDecimal |> .decoder)
