-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Order exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


customerNumber : SelectionSet (Maybe Int) Api.Object.Order
customerNumber =
    Object.selectionForField "(Maybe Int)" "customerNumber" [] (Decode.int |> Decode.nullable)


id : SelectionSet (Maybe Api.ScalarCodecs.Id) Api.Object.Order
id =
    Object.selectionForField "(Maybe ScalarCodecs.Id)" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder |> Decode.nullable)


items :
    SelectionSet decodesTo Api.Object.OrderItem
    -> SelectionSet (Maybe (List (Maybe decodesTo))) Api.Object.Order
items object_ =
    Object.selectionForCompositeField "items" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


state : SelectionSet (Maybe String) Api.Object.Order
state =
    Object.selectionForField "(Maybe String)" "state" [] (Decode.string |> Decode.nullable)
